### PR TITLE
Fix the extension on everyone's but Daniel's computer

### PR DESCRIPTION
**Pull request by adamziel**
Solves #1

* Removes the build pipeline which hardcoded the paths.
* Abstract server.js from the extension.js
* Remove the VS code tab, only open the playground in the actual web browser

May not need to merge this PR – I'd like to move this extension over to the canonical WordPress Playground repo

cc @dmsnell

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> I'd like to move this extension over to the canonical WordPress Playground repo

@adamziel I'm fine with this, whenever you might want to take it on.

**Comment by jonathanbossenger** [comment]
I tested this update today and it works!

**Comment by danielbachhuber** [comment]
> Remove the VS code tab, only open the playground in the actual web browser

@adamziel I liked launching in VS Code for the demo effect. It was a little bit jarring to load directly in the browser.

What do you think about opening in VS Code by default, and having a button that says "Open in browser" within that pane?

**Comment by dmsnell** [comment]
@danielbachhuber the demo effect might be nice, but I've found it practically frustrating because of the lack of browser dev tools and navigation support, opening new tabs, etc…

I'd rather keep the default to the browser, but I don't see why we couldn't also include a second command to launch directly in VSCode.

What about opening a new browser tab to the launched WordPress do you find less appealing?

**Comment by danielbachhuber** [comment]
> What about opening a new browser tab to the launched WordPress do you find less appealing?

It wasn't the behavior I expected. Additionally, there wasn't an obvious indication that the website I redirected to had anything to do with my codebase.

**Comment by dmsnell** [comment]
maybe two commands would work best then: "Launch playground" and "Launch playground (inside VSCode)"

the in-VSCode environment is almost unusable from a development perspective because of the limitations of that browser (as I noted above)

**Comment by adamziel** [comment]
I like launching inside VS code to show that it works, but I would absolutely hate using that for actual development. The browser has amazing developer tools and plugins and it would be a shame to prevent people from using those. Two execution modes sound like a good compromise.

**Comment by danielbachhuber** [comment]
> Two execution modes sound like a good compromise.

I have an idea on how to do this.

**Comment by adamziel** [comment]
This is now ported to WordPress Playground repo – this repo can be deleted.

https://github.com/WordPress/wordpress-playground/pull/288

**Comment by danielbachhuber** [comment]
@adamziel Thanks! I will archive the repo for historical purposes.

**Pull request closed without merging**
